<?xml version="1.0" encoding="utf-8"?><Database Name="ClimbingDatabase" Class="ClimbingDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Climber" Member="Climbers">
    <Type Name="Climber">
      <Column Name="ClimberID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Climber_NetUser" Member="NetUsers" ThisKey="ClimberID" OtherKey="ClimberID" Type="NetUser" />
      <Association Name="Climber_Table" Member="Tables" ThisKey="ClimberID" OtherKey="ClimberID" Type="Table" />
      <Association Name="Climber_Send" Member="Sends" ThisKey="ClimberID" OtherKey="ClimberID" Type="Send" />
    </Type>
  </Table>
  <Table Name="dbo.Grades" Member="Grades">
    <Type Name="Grade">
      <Column Name="GradeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GradeDescription" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Grade_Route" Member="Routes" ThisKey="GradeID" OtherKey="GradeID" Type="Route" />
    </Type>
  </Table>
  <Table Name="dbo.LocationTable" Member="LocationTables">
    <Type Name="LocationTable">
      <Column Name="LocationID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StateName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="LocationTable_Route" Member="Routes" ThisKey="LocationID" OtherKey="LocationID" Type="Route" />
    </Type>
  </Table>
  <Table Name="dbo.NetUser" Member="NetUsers">
    <Type Name="NetUser">
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PasswordValue" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ClimberID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Climber_NetUser" Member="Climber" ThisKey="ClimberID" OtherKey="ClimberID" Type="Climber" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Table]" Member="Tables">
    <Type Name="Table">
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PasswordValue" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ClimberID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Climber_Table" Member="Climber" ThisKey="ClimberID" OtherKey="ClimberID" Type="Climber" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Route" Member="Routes">
    <Type Name="Route">
      <Column Name="RouteID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LocationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GradeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Route_Send" Member="Sends" ThisKey="RouteID" OtherKey="RouteID" Type="Send" />
      <Association Name="Grade_Route" Member="Grade" ThisKey="GradeID" OtherKey="GradeID" Type="Grade" IsForeignKey="true" />
      <Association Name="LocationTable_Route" Member="LocationTable" ThisKey="LocationID" OtherKey="LocationID" Type="LocationTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Sends" Member="Sends">
    <Type Name="Send">
      <Column Name="SendID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ClimberID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RouteID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Attempts" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Climber_Send" Member="Climber" ThisKey="ClimberID" OtherKey="ClimberID" Type="Climber" IsForeignKey="true" />
      <Association Name="Route_Send" Member="Route" ThisKey="RouteID" OtherKey="RouteID" Type="Route" IsForeignKey="true" />
    </Type>
  </Table>
</Database>